import { createContext, useContext } from 'react';

const en = {
  appName: 'Phone Parts', dashboard: 'Dashboard', inventory: 'Inventory', stockCount: 'Stock Count', caisse: 'Caisse', debts: 'Supplier Debts', reports: 'Reports', notes: 'Notes', settings: 'Settings', more: 'More', clients: 'Clients', audit: 'Audit Trail',
  search: 'Search', searchPlaceholder: 'Search part, brand, model, barcode…', noResults: 'No results', loading: 'Loading…', retry: 'Retry', serverUnreachable: 'Server unreachable. Check your connection.', dataChanged: 'Data changed on another device. Refreshed.',
  save: 'Save', cancel: 'Cancel', close: 'Close', confirm: 'Confirm', delete: 'Delete', restore: 'Restore', edit: 'Edit', copy: 'Copy', add: 'Add', back: 'Back', next: 'Next', yes: 'Yes', no: 'No', actions: 'Actions', all: 'All', none: 'None', optional: 'optional', required: 'Required', invalid: 'Invalid value', taken: 'Already in use', duplicate: 'Duplicate in batch', min3: 'At least 3 characters', min6: 'At least 6 characters', copied: 'Copied to clipboard', saved: 'Saved', done: 'Done', showDeleted: 'Show deleted', perPage: 'per page', of: 'of', page: 'Page', total: 'Total', date: 'Date', description: 'Description', amount: 'Amount', status: 'Status', name: 'Name', phone: 'Phone', address: 'Address',
  totalProducts: 'Products', totalUnits: 'Units in stock', stockValue: 'Stock value (cost)', hide: 'Hide', show: 'Show', lowStock: 'Low stock', outOfStock: 'Out of stock', copyList: 'Copy list', inStock: 'In stock', quickSearch: 'Quick search', allGood: 'All good — nothing here.',
  addProduct: 'Add product', addMultiple: 'Add multiple', partName: 'Part name', category: 'Category', model: 'Compatible model', costPrice: 'Cost price', sellingPrice: 'Selling price', quantity: 'Quantity', barcode: 'Barcode', autoSku: 'Auto-generated if blank', supplier: 'Supplier', chooseSupplier: 'Choose supplier', supplierRequiredQty: 'Supplier is required when the initial quantity is above 0', restock: 'Restock', use: 'Use', useOne: 'Use 1 unit', details: 'Details', deleted: 'Deleted', deleteProductHint: 'Only products with quantity 0 can be deleted.', restoreProduct: 'Restore product', productDeleted: 'This product is deleted. Restore it to use or restock it.', productRestored: 'Product restored', productSaved: 'Product saved', copyProduct: 'Copy product', readOnlyEdit: 'Cost and quantity change only through restock, use or return.', restockQty: 'Quantity to add', unitCost: 'Unit cost', updateSelling: 'Update selling price (optional)', restockCreatesDebt: 'This creates a supplier debt of', newAvgCost: 'New average cost', restocked: 'Restocked', cancelRestock: 'Cancel restock', cancelRestockHint: 'Allowed only if the debt is unpaid and no later sale, return or restock exists.', restockCancelled: 'Restock cancelled', restockHistory: 'Restock history', salesHistory: 'Sales history', rows: 'Rows', addRow: 'Add row', removeRow: 'Remove', bulkHint: 'One supplier for the whole batch, up to 50 rows. Saved all-or-nothing.', bulkSaved: 'products added', filter: 'Filter', stock: 'Stock', low: 'Low', out: 'Out', cancelled: 'Cancelled', active: 'Active', paidDebt: 'Debt paid',
  price: 'Price', clientName: 'Client name', passenger: 'passenger', paid: 'Paid', unpaid: 'Unpaid', confirmUse: 'Confirm use', belowCost: 'Price is below cost', used: 'Part used', remaining: 'remaining', printReceipt: 'Print receipt', receipt: 'Receipt', return: 'Return', returned: 'Returned', returnConfirm: 'Return this part? The unit goes back to stock. If it was paid, the amount is refunded from the Caisse.', returnDone: 'Return recorded', refunded: 'refunded', outOfStockErr: 'Out of stock', markPaid: 'Mark paid', markPaidConfirm: 'Confirm payment collected?', paidNow: 'Payment recorded', editPrice: 'Edit price', priceLocked: 'Price locked (paid)', usedParts: 'Used parts', client: 'Client', part: 'Part', payment: 'Payment', purchases: 'Purchases', totalSpent: 'Total spent', clientHistory: 'Client history', lastPurchase: 'Last purchase',
  balance: 'Balance', collected: 'Collected', refunds: 'Refunds', unpaidUsed: 'Unpaid used parts', totalAssets: 'Total assets', expenses: 'Expenses', withdrawals: 'Withdrawals', outstandingDebt: 'Outstanding supplier debt', paidToSuppliers: 'Paid to suppliers', capital: 'Capital', addExpense: 'Add expense', addWithdrawal: 'Add withdrawal', reason: 'Reason', negativeWarn: 'This will make the balance negative', negativeConfirm: 'Balance will go negative. Continue?', entryAdded: 'Entry added', cancelEntry: 'Cancel entry', cancelEntryConfirm: 'Cancel this entry? A linked reversal will be created and it will be excluded from totals.', entryCancelled: 'Entry cancelled', reversal: 'Reversal', summary: 'Summary', balanceFormula: 'balance = capital + collected − refunds − expenses − withdrawals − paid to suppliers',
  recordPayment: 'Record payment', paidSoFar: 'Paid so far', remainingDebt: 'Remaining', paymentHistory: 'Payment history', debtHistory: 'Debt history', exceedsDebt: 'Payment cannot exceed remaining debt', fifoHint: 'Partial payments apply to the oldest debt first.', paymentRecorded: 'Payment recorded', noDebts: 'No supplier debts.', note: 'Note', open: 'Open',
  systemQty: 'System qty', countedQty: 'Counted', difference: 'Difference', surplus: 'Surplus', missing: 'Missing', matching: 'Matching', stockCountHint: 'Read-only: counting never changes stock. Enter counted quantities to see differences.', exportPdf: 'Export PDF', exportCsv: 'Export CSV', copyText: 'Copy as text', notCounted: 'Not counted', showOnlyDiff: 'Only differences', report: 'Report',
  newNote: 'New note…', noNotes: 'No notes yet.',
  from: 'From', to: 'To', partsUsed: 'Parts used', cost: 'Cost (snapshots)', revenue: 'Revenue', revenuePaid: 'Revenue (paid)', revenueUnpaid: 'Revenue (unpaid)', profit: 'Profit', topPart: 'Top part', topParts: 'Top parts', count: 'Count', daily: 'Daily breakdown', day: 'Day', profitFormula: 'profit = revenue − cost snapshots − expenses', thisMonth: 'This month', last7: 'Last 7 days', today: 'Today', lastMonth: 'Last month', generate: 'Generate',
  storeName: 'Store name', language: 'Language', theme: 'Theme', dark: 'Dark', light: 'Light', categories: 'Categories', suppliers: 'Suppliers', addCategory: 'Add category', addSupplier: 'Add supplier', supplierHasDebt: 'A supplier with open debt cannot be deleted', capitalHistory: 'Capital change history', from_: 'from', to_: 'to', databaseTools: 'Database tools', backup: 'Download backup (mysqldump)', clean: 'Clean database', cleanWarn: 'This drops ALL app tables and returns to setup. All data will be lost permanently. The saved connection is kept.', cleanCheck: 'I understand this is permanent', cleanBtn: 'Erase everything', changePassword: 'Change password', currentPassword: 'Current password', newPassword: 'New password', passwordChanged: 'Password changed', logout: 'Log out', auditRestricted: 'Audit log is append-only (DB user has no UPDATE/DELETE)', auditNotRestricted: 'Could not create a restricted DB user; audit log protected by application only', entity: 'Entity', action: 'Action', nameTaken: 'This name already exists',
  setupTitle: 'Setup', setupDb: 'MySQL connection', setupStore: 'Store', setupAdmin: 'Admin account', setupFinish: 'Finish', host: 'Host', port: 'Port', user: 'User', password: 'Password', database: 'Database', testConnection: 'Test connection', connectionOk: 'Connected', dbNotEmpty: 'This database already has tables. Use an empty database.', dbEmpty: 'Empty database — ready.', initialCapital: 'Initial capital', username: 'Username', confirmPassword: 'Confirm password', passwordsMismatch: 'Passwords do not match', createTables: 'Create tables & finish', setupDone: 'Setup complete! Please log in.', useSaved: 'Use saved connection', savedConnectionHint: 'A connection was saved before cleaning. You can reuse it.', connectionSavedServer: 'Connection settings stay on the server only.',
  login: 'Log in', loginTitle: 'Welcome back', badCredentials: 'Invalid username or password', welcome: 'Welcome',
  currency: 'TND', items: 'items', refresh: 'Refresh', copyBarcode: 'Copy barcode', seeClient: 'See client', recent: 'Recent', product: 'Product', qty: 'Qty', unitsShort: 'u', emptyList: 'Nothing to show', errorGeneric: 'Something went wrong', tryAgain: 'Please retry.', notFound: 'Not found', collapse: 'Collapse', expand: 'Expand',
};

const fr = {
  ...en,
  appName: 'Pièces Téléphone', dashboard: 'Tableau de bord', inventory: 'Inventaire', stockCount: 'Inventaire physique', caisse: 'Caisse', debts: 'Dettes fournisseurs', reports: 'Rapports', notes: 'Notes', settings: 'Paramètres', more: 'Plus', clients: 'Clients', audit: 'Journal d\'audit',
  search: 'Rechercher', searchPlaceholder: 'Pièce, marque, modèle, code-barres…', noResults: 'Aucun résultat', loading: 'Chargement…', retry: 'Réessayer', serverUnreachable: 'Serveur injoignable. Vérifiez la connexion.', dataChanged: 'Données modifiées sur un autre appareil. Actualisé.',
  save: 'Enregistrer', cancel: 'Annuler', close: 'Fermer', confirm: 'Confirmer', delete: 'Supprimer', restore: 'Restaurer', edit: 'Modifier', copy: 'Copier', add: 'Ajouter', back: 'Retour', next: 'Suivant', yes: 'Oui', no: 'Non', actions: 'Actions', all: 'Tous', none: 'Aucun', optional: 'optionnel', required: 'Obligatoire', invalid: 'Valeur invalide', taken: 'Déjà utilisé', duplicate: 'Doublon dans le lot', min3: 'Au moins 3 caractères', min6: 'Au moins 6 caractères', copied: 'Copié', saved: 'Enregistré', done: 'Fait', showDeleted: 'Afficher supprimés', perPage: 'par page', of: 'sur', page: 'Page', total: 'Total', date: 'Date', description: 'Description', amount: 'Montant', status: 'Statut', name: 'Nom', phone: 'Téléphone', address: 'Adresse',
  totalProducts: 'Produits', totalUnits: 'Unités en stock', stockValue: 'Valeur du stock (coût)', hide: 'Masquer', show: 'Afficher', lowStock: 'Stock faible', outOfStock: 'Rupture', copyList: 'Copier la liste', inStock: 'En stock', quickSearch: 'Recherche rapide', allGood: 'Tout va bien — rien ici.',
  addProduct: 'Ajouter un produit', addMultiple: 'Ajouter plusieurs', partName: 'Nom de la pièce', category: 'Catégorie', model: 'Modèle compatible', costPrice: 'Prix d\'achat', sellingPrice: 'Prix de vente', quantity: 'Quantité', barcode: 'Code-barres', autoSku: 'Généré automatiquement si vide', supplier: 'Fournisseur', chooseSupplier: 'Choisir un fournisseur', supplierRequiredQty: 'Fournisseur requis si la quantité initiale est > 0', restock: 'Réapprovisionner', use: 'Utiliser', useOne: 'Utiliser 1 unité', details: 'Détails', deleted: 'Supprimé', deleteProductHint: 'Seuls les produits à quantité 0 peuvent être supprimés.', restoreProduct: 'Restaurer le produit', productDeleted: 'Produit supprimé. Restaurez-le pour l\'utiliser ou le réapprovisionner.', productRestored: 'Produit restauré', productSaved: 'Produit enregistré', copyProduct: 'Copier le produit', readOnlyEdit: 'Le coût et la quantité changent uniquement par réapprovisionnement, utilisation ou retour.', restockQty: 'Quantité à ajouter', unitCost: 'Coût unitaire', updateSelling: 'Mettre à jour le prix de vente (optionnel)', restockCreatesDebt: 'Crée une dette fournisseur de', newAvgCost: 'Nouveau coût moyen', restocked: 'Réapprovisionné', cancelRestock: 'Annuler le réappro', cancelRestockHint: 'Possible seulement si la dette est impayée et sans vente, retour ou réappro ultérieur.', restockCancelled: 'Réappro annulé', restockHistory: 'Historique des réappros', salesHistory: 'Historique des ventes', rows: 'Lignes', addRow: 'Ajouter une ligne', removeRow: 'Retirer', bulkHint: 'Un fournisseur pour tout le lot, max 50 lignes. Tout ou rien.', bulkSaved: 'produits ajoutés', filter: 'Filtrer', stock: 'Stock', low: 'Faible', out: 'Rupture', cancelled: 'Annulé', active: 'Actif', paidDebt: 'Dette payée',
  price: 'Prix', clientName: 'Nom du client', passenger: 'passager', paid: 'Payé', unpaid: 'Impayé', confirmUse: 'Confirmer l\'utilisation', belowCost: 'Prix inférieur au coût', used: 'Pièce utilisée', remaining: 'restant', printReceipt: 'Imprimer le reçu', receipt: 'Reçu', return: 'Retour', returned: 'Retourné', returnConfirm: 'Retourner cette pièce ? L\'unité revient en stock. Si payée, le montant est remboursé depuis la caisse.', returnDone: 'Retour enregistré', refunded: 'remboursé', outOfStockErr: 'Rupture de stock', markPaid: 'Marquer payé', markPaidConfirm: 'Confirmer le paiement encaissé ?', paidNow: 'Paiement enregistré', editPrice: 'Modifier le prix', priceLocked: 'Prix verrouillé (payé)', usedParts: 'Pièces utilisées', client: 'Client', part: 'Pièce', payment: 'Paiement', purchases: 'Achats', totalSpent: 'Total dépensé', clientHistory: 'Historique client', lastPurchase: 'Dernier achat',
  balance: 'Solde', collected: 'Encaissé', refunds: 'Remboursements', unpaidUsed: 'Pièces impayées', totalAssets: 'Actif total', expenses: 'Dépenses', withdrawals: 'Retraits', outstandingDebt: 'Dette fournisseurs', paidToSuppliers: 'Payé aux fournisseurs', capital: 'Capital', addExpense: 'Ajouter une dépense', addWithdrawal: 'Ajouter un retrait', reason: 'Motif', negativeWarn: 'Le solde deviendra négatif', negativeConfirm: 'Le solde sera négatif. Continuer ?', entryAdded: 'Entrée ajoutée', cancelEntry: 'Annuler l\'entrée', cancelEntryConfirm: 'Annuler cette entrée ? Une contre-écriture liée sera créée et exclue des totaux.', entryCancelled: 'Entrée annulée', reversal: 'Contre-écriture', summary: 'Résumé', balanceFormula: 'solde = capital + encaissé − remboursements − dépenses − retraits − payé aux fournisseurs',
  recordPayment: 'Enregistrer un paiement', paidSoFar: 'Payé', remainingDebt: 'Restant', paymentHistory: 'Historique des paiements', debtHistory: 'Historique des dettes', exceedsDebt: 'Le paiement dépasse la dette restante', fifoHint: 'Les paiements partiels s\'appliquent d\'abord à la dette la plus ancienne.', paymentRecorded: 'Paiement enregistré', noDebts: 'Aucune dette fournisseur.', note: 'Note', open: 'Ouverte',
  systemQty: 'Qté système', countedQty: 'Comptée', difference: 'Écart', surplus: 'Excédent', missing: 'Manquant', matching: 'Conforme', stockCountHint: 'Lecture seule : le comptage ne modifie jamais le stock.', exportPdf: 'Exporter PDF', exportCsv: 'Exporter CSV', copyText: 'Copier en texte', notCounted: 'Non compté', showOnlyDiff: 'Écarts seulement', report: 'Rapport',
  newNote: 'Nouvelle note…', noNotes: 'Pas encore de notes.',
  from: 'Du', to: 'Au', partsUsed: 'Pièces utilisées', cost: 'Coût (instantanés)', revenue: 'Revenu', revenuePaid: 'Revenu (payé)', revenueUnpaid: 'Revenu (impayé)', profit: 'Bénéfice', topPart: 'Pièce la plus vendue', topParts: 'Meilleures pièces', count: 'Nombre', daily: 'Détail journalier', day: 'Jour', profitFormula: 'bénéfice = revenu − coûts − dépenses', thisMonth: 'Ce mois', last7: '7 derniers jours', today: 'Aujourd\'hui', lastMonth: 'Mois dernier', generate: 'Générer',
  storeName: 'Nom du magasin', language: 'Langue', theme: 'Thème', dark: 'Sombre', light: 'Clair', categories: 'Catégories', suppliers: 'Fournisseurs', addCategory: 'Ajouter une catégorie', addSupplier: 'Ajouter un fournisseur', supplierHasDebt: 'Un fournisseur avec dette ouverte ne peut pas être supprimé', capitalHistory: 'Historique du capital', from_: 'de', to_: 'à', databaseTools: 'Outils base de données', backup: 'Télécharger une sauvegarde (mysqldump)', clean: 'Nettoyer la base', cleanWarn: 'Supprime TOUTES les tables de l\'app et revient à l\'installation. Perte définitive des données. La connexion enregistrée est conservée.', cleanCheck: 'Je comprends que c\'est irréversible', cleanBtn: 'Tout effacer', changePassword: 'Changer le mot de passe', currentPassword: 'Mot de passe actuel', newPassword: 'Nouveau mot de passe', passwordChanged: 'Mot de passe changé', logout: 'Se déconnecter', auditRestricted: 'Journal d\'audit en ajout seul (utilisateur DB sans UPDATE/DELETE)', auditNotRestricted: 'Impossible de créer un utilisateur DB restreint ; journal protégé par l\'application seulement', entity: 'Entité', action: 'Action', nameTaken: 'Ce nom existe déjà',
  setupTitle: 'Installation', setupDb: 'Connexion MySQL', setupStore: 'Magasin', setupAdmin: 'Compte admin', setupFinish: 'Terminer', host: 'Hôte', port: 'Port', user: 'Utilisateur', password: 'Mot de passe', database: 'Base de données', testConnection: 'Tester la connexion', connectionOk: 'Connecté', dbNotEmpty: 'Cette base contient déjà des tables. Utilisez une base vide.', dbEmpty: 'Base vide — prête.', initialCapital: 'Capital initial', username: 'Nom d\'utilisateur', confirmPassword: 'Confirmer le mot de passe', passwordsMismatch: 'Les mots de passe ne correspondent pas', createTables: 'Créer les tables et terminer', setupDone: 'Installation terminée ! Connectez-vous.', useSaved: 'Utiliser la connexion enregistrée', savedConnectionHint: 'Une connexion a été enregistrée avant le nettoyage. Vous pouvez la réutiliser.', connectionSavedServer: 'Les paramètres de connexion restent sur le serveur uniquement.',
  login: 'Se connecter', loginTitle: 'Bon retour', badCredentials: 'Identifiants invalides', welcome: 'Bienvenue',
  currency: 'TND', items: 'éléments', refresh: 'Actualiser', copyBarcode: 'Copier le code-barres', seeClient: 'Voir le client', recent: 'Récent', product: 'Produit', qty: 'Qté', unitsShort: 'u', emptyList: 'Rien à afficher', errorGeneric: 'Une erreur est survenue', tryAgain: 'Veuillez réessayer.', notFound: 'Introuvable', collapse: 'Réduire', expand: 'Agrandir',
};

const ar = {
  ...en,
  appName: 'قطع الهواتف', dashboard: 'لوحة التحكم', inventory: 'المخزون', stockCount: 'جرد المخزون', caisse: 'الصندوق', debts: 'ديون الموردين', reports: 'التقارير', notes: 'ملاحظات', settings: 'الإعدادات', more: 'المزيد', clients: 'العملاء', audit: 'سجل التدقيق',
  search: 'بحث', searchPlaceholder: 'قطعة، علامة، موديل، باركود…', noResults: 'لا توجد نتائج', loading: 'جارٍ التحميل…', retry: 'إعادة المحاولة', serverUnreachable: 'لا يمكن الوصول إلى الخادم. تحقق من الاتصال.', dataChanged: 'تغيرت البيانات على جهاز آخر. تم التحديث.',
  save: 'حفظ', cancel: 'إلغاء', close: 'إغلاق', confirm: 'تأكيد', delete: 'حذف', restore: 'استرجاع', edit: 'تعديل', copy: 'نسخ', add: 'إضافة', back: 'رجوع', next: 'التالي', yes: 'نعم', no: 'لا', actions: 'إجراءات', all: 'الكل', none: 'لا شيء', optional: 'اختياري', required: 'مطلوب', invalid: 'قيمة غير صالحة', taken: 'مستخدم مسبقاً', duplicate: 'مكرر في الدفعة', min3: '3 أحرف على الأقل', min6: '6 أحرف على الأقل', copied: 'تم النسخ', saved: 'تم الحفظ', done: 'تم', showDeleted: 'عرض المحذوف', perPage: 'لكل صفحة', of: 'من', page: 'صفحة', total: 'الإجمالي', date: 'التاريخ', description: 'الوصف', amount: 'المبلغ', status: 'الحالة', name: 'الاسم', phone: 'الهاتف', address: 'العنوان',
  totalProducts: 'المنتجات', totalUnits: 'الوحدات في المخزون', stockValue: 'قيمة المخزون (التكلفة)', hide: 'إخفاء', show: 'عرض', lowStock: 'مخزون منخفض', outOfStock: 'نفد المخزون', copyList: 'نسخ القائمة', inStock: 'متوفر', quickSearch: 'بحث سريع', allGood: 'كل شيء جيد — لا شيء هنا.',
  addProduct: 'إضافة منتج', addMultiple: 'إضافة عدة منتجات', partName: 'اسم القطعة', category: 'الفئة', model: 'الموديل المتوافق', costPrice: 'سعر التكلفة', sellingPrice: 'سعر البيع', quantity: 'الكمية', barcode: 'الباركود', autoSku: 'يُولَّد تلقائياً إذا تُرك فارغاً', supplier: 'المورد', chooseSupplier: 'اختر المورد', supplierRequiredQty: 'المورد مطلوب عندما تكون الكمية الأولية أكبر من 0', restock: 'إعادة التخزين', use: 'استخدام', useOne: 'استخدام وحدة واحدة', details: 'التفاصيل', deleted: 'محذوف', deleteProductHint: 'يمكن حذف المنتجات ذات الكمية 0 فقط.', restoreProduct: 'استرجاع المنتج', productDeleted: 'هذا المنتج محذوف. استرجعه لاستخدامه أو إعادة تخزينه.', productRestored: 'تم استرجاع المنتج', productSaved: 'تم حفظ المنتج', copyProduct: 'نسخ المنتج', readOnlyEdit: 'التكلفة والكمية تتغيران فقط عبر إعادة التخزين أو الاستخدام أو الإرجاع.', restockQty: 'الكمية المضافة', unitCost: 'تكلفة الوحدة', updateSelling: 'تحديث سعر البيع (اختياري)', restockCreatesDebt: 'ينشئ دين مورد بقيمة', newAvgCost: 'التكلفة المتوسطة الجديدة', restocked: 'تمت إعادة التخزين', cancelRestock: 'إلغاء إعادة التخزين', cancelRestockHint: 'مسموح فقط إذا كان الدين غير مدفوع ولا توجد عملية بيع أو إرجاع أو إعادة تخزين لاحقة.', restockCancelled: 'تم إلغاء إعادة التخزين', restockHistory: 'سجل إعادة التخزين', salesHistory: 'سجل المبيعات', rows: 'الصفوف', addRow: 'إضافة صف', removeRow: 'إزالة', bulkHint: 'مورد واحد للدفعة كاملة، حتى 50 صفاً. يُحفظ الكل أو لا شيء.', bulkSaved: 'منتجات أُضيفت', filter: 'تصفية', stock: 'المخزون', low: 'منخفض', out: 'نفد', cancelled: 'ملغى', active: 'نشط', paidDebt: 'الدين مدفوع',
  price: 'السعر', clientName: 'اسم العميل', passenger: 'عابر', paid: 'مدفوع', unpaid: 'غير مدفوع', confirmUse: 'تأكيد الاستخدام', belowCost: 'السعر أقل من التكلفة', used: 'تم استخدام القطعة', remaining: 'متبقٍ', printReceipt: 'طباعة الوصل', receipt: 'وصل', return: 'إرجاع', returned: 'مُرجَع', returnConfirm: 'إرجاع هذه القطعة؟ تعود الوحدة إلى المخزون. إذا كانت مدفوعة يُرد المبلغ من الصندوق.', returnDone: 'تم تسجيل الإرجاع', refunded: 'مُستردّ', outOfStockErr: 'نفد المخزون', markPaid: 'تحديد كمدفوع', markPaidConfirm: 'تأكيد استلام الدفع؟', paidNow: 'تم تسجيل الدفع', editPrice: 'تعديل السعر', priceLocked: 'السعر مقفل (مدفوع)', usedParts: 'القطع المستخدمة', client: 'العميل', part: 'القطعة', payment: 'الدفع', purchases: 'المشتريات', totalSpent: 'إجمالي المصروف', clientHistory: 'سجل العميل', lastPurchase: 'آخر عملية شراء',
  balance: 'الرصيد', collected: 'المحصَّل', refunds: 'المبالغ المستردة', unpaidUsed: 'قطع مستخدمة غير مدفوعة', totalAssets: 'إجمالي الأصول', expenses: 'المصاريف', withdrawals: 'المسحوبات', outstandingDebt: 'ديون الموردين المستحقة', paidToSuppliers: 'المدفوع للموردين', capital: 'رأس المال', addExpense: 'إضافة مصروف', addWithdrawal: 'إضافة سحب', reason: 'السبب', negativeWarn: 'سيصبح الرصيد سالباً', negativeConfirm: 'سيصبح الرصيد سالباً. متابعة؟', entryAdded: 'تمت الإضافة', cancelEntry: 'إلغاء القيد', cancelEntryConfirm: 'إلغاء هذا القيد؟ سيُنشأ قيد عكسي مرتبط ويُستثنى من الإجماليات.', entryCancelled: 'تم إلغاء القيد', reversal: 'قيد عكسي', summary: 'ملخص', balanceFormula: 'الرصيد = رأس المال + المحصَّل − المستردّ − المصاريف − المسحوبات − المدفوع للموردين',
  recordPayment: 'تسجيل دفعة', paidSoFar: 'المدفوع', remainingDebt: 'المتبقي', paymentHistory: 'سجل الدفعات', debtHistory: 'سجل الديون', exceedsDebt: 'لا يمكن أن تتجاوز الدفعة الدين المتبقي', fifoHint: 'تُطبَّق الدفعات الجزئية على أقدم دين أولاً.', paymentRecorded: 'تم تسجيل الدفعة', noDebts: 'لا توجد ديون موردين.', note: 'ملاحظة', open: 'مفتوح',
  systemQty: 'كمية النظام', countedQty: 'المعدودة', difference: 'الفرق', surplus: 'فائض', missing: 'ناقص', matching: 'مطابق', stockCountHint: 'للقراءة فقط: الجرد لا يغيّر المخزون أبداً.', exportPdf: 'تصدير PDF', exportCsv: 'تصدير CSV', copyText: 'نسخ كنص', notCounted: 'غير معدود', showOnlyDiff: 'الفروق فقط', report: 'تقرير',
  newNote: 'ملاحظة جديدة…', noNotes: 'لا توجد ملاحظات بعد.',
  from: 'من', to: 'إلى', partsUsed: 'القطع المستخدمة', cost: 'التكلفة (اللقطات)', revenue: 'الإيرادات', revenuePaid: 'الإيرادات (مدفوعة)', revenueUnpaid: 'الإيرادات (غير مدفوعة)', profit: 'الربح', topPart: 'أكثر قطعة', topParts: 'أفضل القطع', count: 'العدد', daily: 'التفصيل اليومي', day: 'اليوم', profitFormula: 'الربح = الإيرادات − التكلفة − المصاريف', thisMonth: 'هذا الشهر', last7: 'آخر 7 أيام', today: 'اليوم', lastMonth: 'الشهر الماضي', generate: 'إنشاء',
  storeName: 'اسم المتجر', language: 'اللغة', theme: 'المظهر', dark: 'داكن', light: 'فاتح', categories: 'الفئات', suppliers: 'الموردون', addCategory: 'إضافة فئة', addSupplier: 'إضافة مورد', supplierHasDebt: 'لا يمكن حذف مورد لديه دين مفتوح', capitalHistory: 'سجل تغيير رأس المال', from_: 'من', to_: 'إلى', databaseTools: 'أدوات قاعدة البيانات', backup: 'تنزيل نسخة احتياطية (mysqldump)', clean: 'تنظيف قاعدة البيانات', cleanWarn: 'يحذف جميع جداول التطبيق ويعود إلى الإعداد. ستُفقد البيانات نهائياً. يُحتفظ بالاتصال المحفوظ.', cleanCheck: 'أفهم أن هذا الإجراء نهائي', cleanBtn: 'مسح كل شيء', changePassword: 'تغيير كلمة المرور', currentPassword: 'كلمة المرور الحالية', newPassword: 'كلمة المرور الجديدة', passwordChanged: 'تم تغيير كلمة المرور', logout: 'تسجيل الخروج', auditRestricted: 'سجل التدقيق للإضافة فقط (مستخدم قاعدة البيانات بدون UPDATE/DELETE)', auditNotRestricted: 'تعذر إنشاء مستخدم قاعدة بيانات مقيّد؛ السجل محمي بالتطبيق فقط', entity: 'الكيان', action: 'الإجراء', nameTaken: 'هذا الاسم موجود مسبقاً',
  setupTitle: 'الإعداد', setupDb: 'اتصال MySQL', setupStore: 'المتجر', setupAdmin: 'حساب المدير', setupFinish: 'إنهاء', host: 'المضيف', port: 'المنفذ', user: 'المستخدم', password: 'كلمة المرور', database: 'قاعدة البيانات', testConnection: 'اختبار الاتصال', connectionOk: 'متصل', dbNotEmpty: 'قاعدة البيانات تحتوي جداول بالفعل. استخدم قاعدة فارغة.', dbEmpty: 'قاعدة بيانات فارغة — جاهزة.', initialCapital: 'رأس المال الأولي', username: 'اسم المستخدم', confirmPassword: 'تأكيد كلمة المرور', passwordsMismatch: 'كلمتا المرور غير متطابقتين', createTables: 'إنشاء الجداول والإنهاء', setupDone: 'تم الإعداد! يرجى تسجيل الدخول.', useSaved: 'استخدام الاتصال المحفوظ', savedConnectionHint: 'تم حفظ اتصال قبل التنظيف. يمكنك إعادة استخدامه.', connectionSavedServer: 'إعدادات الاتصال تبقى على الخادم فقط.',
  login: 'تسجيل الدخول', loginTitle: 'مرحباً بعودتك', badCredentials: 'اسم المستخدم أو كلمة المرور غير صحيحة', welcome: 'مرحباً',
  currency: 'د.ت', items: 'عناصر', refresh: 'تحديث', copyBarcode: 'نسخ الباركود', seeClient: 'عرض العميل', recent: 'الأخيرة', product: 'المنتج', qty: 'الكمية', unitsShort: 'و', emptyList: 'لا شيء للعرض', errorGeneric: 'حدث خطأ ما', tryAgain: 'يرجى إعادة المحاولة.', notFound: 'غير موجود', collapse: 'طيّ', expand: 'توسيع',
};

export const LANGS = { en, fr, ar };
export const LANG_NAMES = { en: 'English', fr: 'Français', ar: 'العربية' };
export const I18nContext = createContext({ t: (k) => k, lang: 'en', setLang: () => {} });
export const useT = () => useContext(I18nContext);

export function makeT(lang) { const d = LANGS[lang] || en; return (k) => (d[k] !== undefined ? d[k] : en[k] !== undefined ? en[k] : k); }
export function fmtMoney(v, lang) {
  const n = Number(v) || 0;
  const s = new Intl.NumberFormat(lang === 'ar' ? 'ar-TN' : lang === 'fr' ? 'fr-TN' : 'en-TN', { minimumFractionDigits: 0, maximumFractionDigits: 2 }).format(n);
  return `${s} ${LANGS[lang]?.currency || 'TND'}`;
}
export function fmtDate(v, lang, withTime = true) {
  if (!v) return '';
  const d = new Date(typeof v === 'string' && !v.endsWith('Z') && !v.includes('+') ? v.replace(' ', 'T') + 'Z' : v);
  if (isNaN(d.getTime())) return String(v);
  return d.toLocaleString(lang === 'ar' ? 'ar-TN' : lang === 'fr' ? 'fr-FR' : 'en-GB', withTime ? { dateStyle: 'short', timeStyle: 'short' } : { dateStyle: 'medium' });
}